name: Prepare and test Python

on:
  pull_request:
    branches: [main]

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    
    - name: setup python
      uses: CorporalCiprian/todo-template/.github/workflows/build-template.yml
      with: 
        language: 'python'
        version: '3.14'

